### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by liyunrui** [NVIDIA-Merlin/models#1000]
### Bug description

Add dropout in the code but got error

from tensorflow.keras import regularizers
l2_reg = 0.03
dropout = 0.1
model = mm.DLRMModel(
    schema,
    embedding_dim=64,
    bottom_block=mm.MLPBlock([128, 64], dropout=0.2, kernel_regularizer=tf.keras.regularizers.L2(l2=l2_reg)),
    top_block=mm.MLPBlock([128, 64, 32], kernel_regularizer=tf.keras.regularizers.L2(l2=l2_reg)),
    prediction_tasks=mm.BinaryOutput(target_column),
)

It raise AttributeError: 'Dropout' object has no attribute 'units'

**Comment by rnyak** [comment]
closing since this was solved via https://github.com/NVIDIA-Merlin/models/pull/1018.
