### ISSUE TITLE
RFC on Pairwise losses and negative sampling

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/models#103]

**Comment by EvenOldridge** [comment]
@gabrielspmoreira where are we at on this.  Is this going to be a part of 22.03?

**Comment by EvenOldridge** [comment]
Can you please fill in more details.

**Comment by gabrielspmoreira** [comment]
@EvenOldridge, I have started drafting that RFC [here](https://docs.google.com/document/d/1IWiRPGXizDsU6_M9Xl4v1WiCIy8aCyigs-OmicVAHBI/edit), based on the survey on negative sampling and losses functions I have done [here](https://docs.google.com/document/d/1Tf3p74PyVBnSMFwKIXnO5ASf14Bc6YeFWLoLFjurakQ/edit#heading=h.hj4vln29myg).
I end up discussing the design of the solution directly with @marcromeyn and @sararb in dedicated meetings, and implemented them next.
Not sure if it would make sense to prepare an RFC after the change was already implemented.

But for sure I am going to prepare a dedicated article for our Merlin Models documentation, explaining the available options for neg sampling and loss functions, as described in #201.

Could we maybe close this issue and focus in #201 for 22.04 release?
