### ISSUE TITLE
[QST] Merlin models support for PyTorch

### ISSUE THREAD

**Issue by adhiiisetiawan** [NVIDIA-Merlin/models#1107]
# ❓ Questions & Help

## Details

I have come across the following statement in the README file of the Merlin Models repository: "In our initial releases, Merlin Models features a TensorFlow API. The PyTorch API is initiated, but incomplete." This indicates that while there is some progress in implementing a PyTorch API for Merlin Models, it may not be fully functional or comprehensive at this time. right?

Considering this information, I would like to inquire about the current state of the PyTorch API for Merlin Models. Are there any updates or developments regarding its completeness and usability? If it is still a work in progress, is there an estimated timeline for when the PyTorch API will be fully supported?

Thank you for your attention to this matter. I look forward to your response.

**Comment by rnyak** [comment]
@adhiiisetiawan thanks for your question. We are currently working on PyTorch API  code. It is not ready yet and it will take 1-2 releases to create the examples and documentation around the API usage.

**Comment by adhiiisetiawan** [comment]
Thank you for your response and providing an estimated availability for the PyTorch API.

I look forward to the future release that includes the PyTorch API, as it will greatly enhance the usability and compatibility of Merlin Models with PyTorch.
