### ISSUE TITLE
[DOC] YoutubeDNNRetrievalModelV2 working example

### ISSUE THREAD

**Issue by NikhilShaw** [NVIDIA-Merlin/models#1210]
### Report needed documentation

Working example of YoutubeDNNRetrievalModelV2 on one of popular datasets

### Describe the documentation you'd like

Working example for YoutubeDNNRetrievalModelV2 on one of popular datasets

### Steps taken to search for needed documentation\*\*

1. Didn't find working example in [https://nvidia-merlin.github.io/models/stable/index.html](https://nvidia-merlin.github.io/models/stable/index.html)
2. Didn't find any online article (like medium) containing working example of same
3. Didn't find working example in previous issues

**Comment by rnyak** [comment]
@NikhilShaw  hello. We do not have an example for `YoutubeDNNRetrievalModelV2` yet, you can check out this unit [test](https://github.com/NVIDIA-Merlin/models/blob/main/tests/unit/tf/models/test_retrieval.py#L919) and try to customize it if required.

**Comment by rnyak** [comment]
closing due to low activity.
