### ISSUE TITLE
XGBoost Integration

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/models#132]
https://docs.google.com/presentation/d/1jxj9zjeRRu1BJSf8tzaWoQVr5h7HZbOUsSh39Rcwv80/edit#slide=id.g10be2c57ddf\_7\_2

Aha! Link: https://nvaiinfa.aha.io/features/MERLIN-673

**Comment by radekosmulski** [comment]
Hey! I am not sure if this is the right place to post this, @bschifferer asked me to work on an example for the `xgboost` integration and I left some thoughts in a PR #522. Not sure on the process side of things, where things should go or if what I share there can be helpful, if I am doing something wrong or these thoughts are not adding value, please let me know 🙂Thank you!

**Comment by radekosmulski** [comment]
I am not sure if I should have linked my PR here in the first place, but the three of us (@bschifferer, @oliverholworthy, and me) just had a great chat, I also now know what would be the way to capture all this feedback (via feature requests in Merlin Models), so essentially all is well 🙂
