### ISSUE TITLE
Evaluation - Popularity-bias/novelty metric

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/models#167]
Metrics that computes the popularity bias of the top-n recommended items.
A common choice for this metric is [novelty](https://microsoft-recommenders.readthedocs.io/en/latest/evaluation.html#recommenders.evaluation.python_evaluation.historical_item_novelty) as `-log(norm_prob_item)`, where `norm_prob_item = item_count / total_items_count`, or just the average normalized popularity of top-k items like in [here](https://github.com/jacopotagliabue/reclist/blob/main/reclist/metrics/standard_metrics.py#L106).

The `popularity-bias` metric is also computed based on item popularities. It is describe in the end of page 15 of this [paper](https://arxiv.org/pdf/1803.09587.pdf). That paper implementation of this metric is available [here](https://github.com/rn5l/session-rec/blob/master/evaluation/metrics/popularity.py)

**Comment by rnyak** [comment]
solved by https://github.com/NVIDIA-Merlin/models/pull/371
