### ISSUE TITLE
[BUG] ItemRetrievalTask can’t be saved

### ISSUE THREAD

**Issue by marcromeyn** [NVIDIA-Merlin/models#188]
### Bug description

With this test case:
```python

def test_two_tower_block_saving(ecommerce_data: SyntheticData):
    two_tower = ml.TwoTowerBlock(ecommerce_data.schema, query_tower=ml.MLPBlock([64, 128]))

    model = two_tower.connect(
        ml.ItemRetrievalTask(ecommerce_data.schema, target_name="click", metrics=[])
    )

    dataset = ecommerce_data.tf_dataloader(batch_size=50)
    copy_two_tower = testing_utils.assert_model_is_retrainable(model, dataset)

    outputs = copy_two_tower(ecommerce_data.tf_tensor_dict)
    assert list(outputs.shape) == [100, 1]

```

### Expected behavior
<!-- A clear and concise description of what you expected to happen. —>
Model should be saveable but curently isn’t because `ItemRetrievalScorer` can be saved now.

**Comment by viswa-nvidia** [comment]
Sara could reproduce this issue. @sararb , please provide an update on this.

**Comment by sararb** [comment]
The issue is related to being able to save to disk the custom classes related to `ItemRetrievalTask` and which are: `ItemRetrievalScorer`, `InBatchSampler`,  `CachedCrossBatchSampler`, `CachedUniformSampler` and `PopularityBasedSampler`

**Comment by oliverholworthy** [comment]
The saving of `ItemRetrievalTask` and related layers is now resolved. By #594 and #615 

Loading is still a problem and tracked in #498
