### ISSUE TITLE
[FEA] Install documentation

### ISSUE THREAD

**Issue by albert17** [NVIDIA-Merlin/models#192]
Add documentation about how to install models

**Comment by albert17** [comment]
@marcromeyn We need documentation about installing the software

**Comment by mikemckiernan** [comment]
It's practically impossible to read in diff format, but if Merlin Models is installed with `pip`, `conda`, or customers can use the container images, did I get it correct?

https://github.com/NVIDIA-Merlin/models/pull/193/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17

That's PR https://github.com/NVIDIA-Merlin/models/pull/193.  Please let me know.

**Comment by mikemckiernan** [comment]
Information about installing models is added to the README.
