### ISSUE TITLE
Implement Youtube-DNN ranking model

### ISSUE THREAD

**Issue by sararb** [NVIDIA-Merlin/models#204]
# 🌟 New model addition

## Model description

The youtube-dnn [paper](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45530.pdf) defined a two-stage recommender and proposed  two architectures for retrieval and ranking steps. The purpose of this request is to add the ranking architecture of Youtube-DNN (Figure 7 of the paper) to merlin.models. 

## Open source status

* [ ] the model implementation is available: (give details)
* [ ] the model weights are available: (give details)
* [ ] who are the authors: (mention them, if possible by @gh-username)

**Comment by rnyak** [comment]
tracked via https://github.com/NVIDIA-Merlin/Merlin/issues/279

**Comment by sararb** [comment]
closing this ticket as the scope is more detailed in this RMP [ticket](https://github.com/NVIDIA-Merlin/Merlin/issues/279)
