### ISSUE TITLE
[BUG] For large batch sizes pairwise losses are leading to NaN loss

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/models#252]
I have observed in experiments with large batch sizes (for Ali-CCP and H&M datasets) the pairwise losses sometimes lead to NaN loss.
I am investigating this issue

**Comment by viswa-nvidia** [comment]
It is not a blocker because we are not using pairwise loss functions in the examples. But I am going to check today if this error persists with the latest code and datasets
