### ISSUE TITLE
[FEA]  Get only embeddings from `model.item_embeddings()`

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/models#255]
# 🚀 Feature request

when we run the following command we do not only get item embeddings but also item feature columns in the item_embeddings dataframe. It'd be useful to add an arg in the `item_embeddings()` to exclude other columns.

```
item_embs = model.item_embeddings(Dataset(item_features, schema=schema), batch_size=1024)
item_embs_df = item_embs.compute(scheduler="synchronous")
```
## Motivation

We save item_embeddings for E-2-E and we only want to have the embedding columns. In doing so, we need an extra manual process to drop the item features from the item-embeddings dataframe.

**Comment by karlhigley** [comment]
Has been fixed but PR wasn't linked
