### ISSUE TITLE
[DOC]Models - Docstring bash comments

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/models#318]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-6c1a7ca0-7fff-6057-c832-2531d516bba8"><div dir="ltr" style="margin-left:0pt;" align="left">

Issue | Reported By | Impact | Owner | Status
-- | -- | -- | -- | --
Address TODO comments in retrieval.py and ranking.py. | Marc | L | Marc |  
Fix or investigate intersphinx mappings. Specifically the `Schema` class would be valuable as a link.Ben shared that the NVT workflow page is an example with an intersphinx link to merlin.io.Dataset. | Mike | M | Mike |  

- [x] #319
- [x] #321

**Comment by viswa-nvidia** [comment]
Please take a look at this and close if done

**Comment by bschifferer** [comment]
@viswa-nvidia I think I can close the ticket. There was no progress for >1 year and only one subtask was left.
