### ISSUE TITLE
Address TODO comments in retrieval.py and ranking.py.

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/models#319]

**Comment by viswa-nvidia** [comment]
This is not a blocker.

**Comment by viswa-nvidia** [comment]
background information for beginners.

**Comment by viswa-nvidia** [comment]
@marcromeyn , please close this if this is done.

**Comment by bschifferer** [comment]
@viswa-nvidia I close the ticket, as it is over 1 year old - feel free to reopen, if it is required
