### ISSUE TITLE
Fix or investigate intersphinx mappings.

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/models#321]
Fix or investigate intersphinx mappings. Specifically the Schema class would be valuable as a link.Ben shared that the NVT workflow page is an example with an intersphinx link to merlin.io.Dataset.

**Comment by mikemckiernan** [comment]
This is in the nice-to-have category and not a blocking requirement for any release.

I spotted one mistake (mine) in the models repo, in the `docs/source/conf.py` file, the "main/core" should be "core/main".

```python
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "cudf": ("https://docs.rapids.ai/api/cudf/stable/", None),
    "distributed": ("https://distributed.dask.org/en/latest/", None),
    "torch": ("https://pytorch.org/docs/stable/", None),
    "merlin-core": ("https://nvidia-merlin.github.io/main/core/", None),
}
```

However, making that correction with the latest code in `main` and rebuilding the doc does not make `Schema` in the in API documentation for `DCNModel` into a link to the Merlin Core documentation.

More troubleshooting and research is needed. I want to correct it, but my understanding is that this is a nice-to-have.
