### ISSUE TITLE
[RMP] Performance evaluation and improvements for model training and serving

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/models#346]
### Goal: 
- Easy to evaluate and build performant retrieval and ranking models in production
- Create a performance chart of retrieval and ranking models comparison
  - for Merlin Github repos 

### Retrieval models

- [x] Support model evaluation metrics - MAP, NDCG, Precision, etc (example - [MSFT Recommenders](https://github.com/microsoft/recommenders#algorithm-comparison))
- [ ] Evaluate Training/Inference performance - time to train, serving latency, throughput, etc (example - [JoC PyT DLRM](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Recommendation/DLRM#performance))
- [ ] Performance optimization
  - [ ] https://github.com/NVIDIA-Merlin/models/issues/340 
  - [ ] https://github.com/NVIDIA-Merlin/models/issues/339 
  - [x] https://github.com/NVIDIA-Merlin/models/issues/338
  - [x] https://github.com/NVIDIA-Merlin/models/issues/336

###  Ranking models

- [ ] ???

**Comment by viswa-nvidia** [comment]
@karlhigley , @benfred , I've updated the ticket with the scope and goals that product team captured. I only see tickets related to the third item in the scope i.e.  performance optimization. Which tickets cover the first two items in the scope ? @EvenOldridge for viz.

**Comment by gabrielspmoreira** [comment]
@viswa-nvidia Merlin Models already has the mentioned ranking metrics (MAP, MRR, NDCG, Precision, Recall) implemented [here](https://github.com/NVIDIA-Merlin/models/blob/main/merlin/models/tf/metrics/ranking.py)

**Comment by karlhigley** [comment]
This epic has been split into NVIDIA-Merlin/Merlin#258 and NVIDIA-Merlin/Merlin#259.
