### ISSUE TITLE
[BUG] model.set_retrieval_candidates_for_evaluation(train) for twotower throws AttributeError

### ISSUE THREAD

**Issue by mkumari-ed** [NVIDIA-Merlin/models#366]
### Bug description

model.set_retrieval_candidates_for_evaluation(train) for twotower throws AttributeError: 'RetrievalModel' object has no attribute 'set_retrieval_candidates_for_evaluation'

### Steps/Code to reproduce bug

``` train = Dataset(os.path.join(output_path, "train", "*.parquet"), part_size="200MB")
      model = mm.TwoTowerModel(
      schema,
      query_tower=mm.MLPBlock([128, 64], no_activation_last_layer=True),
      loss="categorical_crossentropy",
      samplers=[mm.InBatchSampler()],
      embedding_options=mm.EmbeddingOptions(infer_embedding_sizes=True),
      metrics=[mm.RecallAt(10), mm.NDCGAt(10)],
  )
model.set_retrieval_candidates_for_evaluation(train)
```

![Screen Shot 2022-04-13 at 9 27 39 PM](https://user-images.githubusercontent.com/28987826/163315312-b643bcee-4066-4f9d-a3b9-7415078a5260.png)

**Comment by mamtaed8811** [comment]
@gabrielspmoreira Thank you for getting back so quick. I tried passing the `item_corpus` inside `model.evaluate()` after `model.fit()` and I get TypeError: `__init__() got an unexpected keyword argument item_corpus`. I did a `git pull` from models/nvtabular/core already and that didn't resolve it.
![Screen Shot 2022-04-14 at 9 29 11 AM](https://user-images.githubusercontent.com/28987826/163433139-8dabcf9f-2524-4ff7-875d-019a683c2262.png)

**Comment by mamtaed8811** [comment]
@gabrielspmoreira  Also, if I do a `model.evaluate()` on validation data without the `item_corpus=train_tt`, then I see a `ValueError: None values not supported`
![Screen Shot 2022-04-14 at 9 36 19 AM](https://user-images.githubusercontent.com/28987826/163439046-98a454af-90b0-47a3-83db-9d3d5abd9f0f.png)
![Screen Shot 2022-04-14 at 9 36 47 AM](https://user-images.githubusercontent.com/28987826/163439068-7c178abd-eabd-4323-be40-9a359fa6e553.png)

**Comment by rnyak** [comment]
it works for me. I dont get error.  Please do the following first in your container to pull the latest changes in the main branch:


```
cd /models
git checkout main
git pull origin main
pip install -e .
```

Then, please try again something like that:

```
metrics = model.evaluate(valid, batch_size=4096, item_corpus=train, return_dict=True)
```

** replace `valid` and `train` with the dataset objects you trained your model.

**Comment by mkumari-ed** [comment]
@rnyak @gabrielspmoreira  I have pulled the latest changes from main branch into my container. Have tried it on both tf-training as well as tf-inference 22.04 containers. I still see the same error on my end. However, it doesn't block me from proceeding with the next steps in the notebook as model.fit works.

**Comment by viswa-nvidia** [comment]
@mkumari-ed , please re open a ticket if you are still facing issues.
