### ISSUE TITLE
[QST] Loading back a trained model

### ISSUE THREAD

**Issue by shoyasaxa** [NVIDIA-Merlin/models#383]
# ❓ Questions & Help

## Details

Hello! 

I have a naive question - once we save a trained model, is it possible to read the model back with the merlin model abstraction (i.e. like a `Model` object from [here](https://github.com/NVIDIA-Merlin/models/blob/99d7e681f7927b8ef30cc920e8e8de1d1d29104d/merlin/models/tf/models/base.py#L157))? I'm aware we can just load it back with `tf.keras.models.load_model()`, but I was wondering if there is a way to load it back as a _Merlin_ Model so that we can still get access to functions like `batch_predict()`. 

Thank you!

**Comment by sararb** [comment]
Hi @shoyasaxa, thank you for your interest in the Merlin Models library. The merlin Model class and all the building blocks are defined with serialization/deserialization functions and are registered as Keras serializable objects. So calling `tf.keras.models.load_model()` will load back the `Merlin` Model class. As a quick example, you can check this unit [test](https://github.com/NVIDIA-Merlin/models/blob/3d1c5e0e72b3f372d16cb4d0ec42a256e68d10fd/tests/tf/test_core.py#L125), where we can access the context block from the loaded saved model.

**Comment by shoyasaxa** [comment]
Hi @sararb, thank you for getting back to me! That makes sense. I will test it out as well!

**Comment by benfred** [comment]
@shoyasaxa let us know if you further questions here -
