### ISSUE TITLE
[Task] Update notebooks to note we require TF 2.8+ in the notebooks.

### ISSUE THREAD

**Issue by benfred** [NVIDIA-Merlin/models#388]
### Description

The notebooks currently include code like

```python
import os
os.environ["TF_GPU_ALLOCATOR"]="cuda_malloc_async"
import merlin.models.tf as mm
```

This causes a segfault in TF 2.6. We should add a note to our notebooks saying that this requires TF 2.8+

**Comment by EvenOldridge** [comment]
And instructions commented out for how to deal with this in 2.6 and lower.

**Comment by rnyak** [comment]
related to https://github.com/NVIDIA-Merlin/Merlin/issues/229

**Comment by rnyak** [comment]
Based on Benedikt's experiment on testbook unit tests, he could avoid Jenkins error after removing `os.environ["TF_GPU_ALLOCATOR"]="cuda_malloc_async" line.

**Comment by viswa-nvidia** [comment]
@benfred , do we need to track this still?

**Comment by bschifferer** [comment]
@viswa-nvidia I closed the ticket, as there is no progress. Please reopen, if we require it.
