### ISSUE TITLE
[BUG] Merlin-Models does not support target variable tagged as `CATEGORICAL`

### ISSUE THREAD

**Issue by sararb** [NVIDIA-Merlin/models#395]
### Bug description
Loading a data with multi-class target variable (Tagged as categorical) throws a key-error: 
```
File /models/merlin/models/loader/backend.py:575, in DataLoader._create_tensors(self, gdf)
    572 if hasattr(column_names, "column_names"):
    573     column_names = column_names.column_names
--> 575 gdf_i = gdf[column_names]
...
File /usr/local/lib/python3.8/dist-packages/cudf/core/column_accessor.py:398, in <dictcomp>(.0)
    397 def _select_by_label_list_like(self, key: Any) -> ColumnAccessor:
--> 398     data = {k: self._grouped_data[k] for k in key}
    399     if self.multiindex:
    400         data = _to_flat_dict(data)

KeyError: 'Post'
```

This error is related to: In Merlin-Models, we assume the target variable does not have a `CATEGORICAL` or `CONTINUOUS` tags. 

### Steps/Code to reproduce bug
This is a basic code to reproduce the bug: 
```
import pandas as pd

import nvtabular as nvt
from merlin.io import Dataset
import merlin.models.tf as mm
from merlin.schema import Schema, Tags

df = pd.DataFrame(
    {
        "Author": ["User_A", "User_E", "User_B", "User_C"],
        "Engaging User": ["User_B", "User_B", "User_A", "User_D"],
        "Post": [1, 2, 3, 4],
    }
)
cat_names = ["Post", ["Author", "Engaging User"]]
cats = cat_names >> nvt.ops.Categorify(encode_type='joint')
target = cats['Post'] >> nvt.ops.AddMetadata(tags=Tags.TARGET)
workflow = nvt.Workflow(cats+target)
df_transform = workflow.fit_transform(Dataset(df))
mm.sample_batch(df_transform, batch_size=2)
```

### Expected behavior
Load data with a categorical target without any error. And exclude target variable from the input block. 

### Additional context
A discussion about how to ensure the target is not selected as an input feature during the data-loading can be found [here](https://github.com/NVIDIA-Merlin/core/issues/75). To keep all information from the pre-processing step, the proposed solution is to add the `excluding` method to the schema so that we can select variables as follow: 
```schema.select_by_tag(Tags.CATEGORICAL).excluding(Tags.TARGET)```

**Comment by viswa-nvidia** [comment]
@sararb , why is this a P0 bug ?  @EvenOldridge , @sohn21c  for vis.
