### ISSUE TITLE
Tweak wrapper for Implicit to account for change surfaced by paper experiments

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/models#410]

**Comment by oliverholworthy** [comment]
@karlhigley or @benfred  can you share the context of what 'change surfaced by paper experiments' refers to for this?

**Comment by benfred** [comment]
We need to be able to weight the input matrix - I added the support in https://github.com/benfred/implicit/pull/581 , which should be enough to close this out now that implicit v0.6.0 is published with this change
