### ISSUE TITLE
[Task] Add booking.com solution to Merlin Models example

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/models#422]
### Description
NVIDIA won the WSDM 2021 competition. As we added new features and libraries, we want to add the solution as Merlin (Models) example:
https://github.com/NVIDIA-Merlin/competitions/tree/main/WSDM_WebTour2021_Challenge/02_Models/GRU_MS_SMF

**Comment by rnyak** [comment]
@viswa-nvidia can we change  the milestone to 22.10?

**Comment by bschifferer** [comment]
Radek provided an example for the new transformer architecture
