### ISSUE TITLE
[BUG] TF Runs out of memory with BYO synthetic dataset

### ISSUE THREAD

**Issue by shoyasaxa** [NVIDIA-Merlin/models#441]
### Bug description  CC: @rnyak 
TF OOMs during the `fit()` call for a synthetic dataset we are trying to experiment with.

Please see the attached `schema.txt` (please convert to `schema.pbtxt` after downloading - Github doesn't support uploading uploading `.pbtxt` files) for the schema of the synthetic dataset we are experimenting with: [schema.txt](https://github.com/NVIDIA-Merlin/models/files/8701457/schema.txt). Our dataset is on the order of billions of rows

### Expected behavior
The model training should not OOM. 

### Environment details
- Merlin version: 0.3.0
- Docker image built from `merlin-training:2022.04`
- cuda: 11.6
- GPU: Just one `V100` with 16GB of RAM 

### Additional context
1. The model we are trying to train is a DLRM from the quick start example.
```
model = mm.DLRMModel(
    schema_train, 
    embedding_dim=64,
    bottom_block=mm.MLPBlock([128, 64]),
    top_block=mm.MLPBlock([128, 64, 32]),
    prediction_tasks=mm.BinaryClassificationTask(
        schema_train.select_by_tag(Tags.TARGET).column_names[0]
    ),
)

model.compile(optimizer="adam")
model.fit(train, batch_size=4096*2, epochs=1)
```

2. Changing the optimizer to something like `adagrad` and `sgd` does let the `fit()` call last longer, but it eventually still OOMs. We have also tried mixed precision training, which helped, but still would eventually fail. 

3. Additionally, from the provided schema, please remove `remove_col1` and `remove_col2` with `schema.remove_col()`. 
4. We had to set `os.environ["TF_GPU_ALLOCATOR"]="cuda_malloc_async"` for training to work even a little
5. We have already reduced some of the column data types from `int64` to `int32` to save space. 

EDIT: 
6. I've also tried reducing the batch size to something smaller, like 64 and training would still eventually fail. I did not, however, try reducing the the `embedding_dim`. But at the same time, memory needed for the embedding tables are around 5M * sizeof(float) * 64 = 1.28GB where sizeof(float) = 4, and this multiplied by 3 for `adam` optimizer states is still only <4GB, so that should still leave 12GB of RAM to train, so it's a bit peculiar.

**Comment by viswa-nvidia** [comment]
@benfred , I understand that you have already started supporting this bug. Please update the ticket.

**Comment by rnyak** [comment]
@shoyasaxa the schema file is missing `item_id` tag. I'd appreciate if you can tag the features `item_id` `user_id`, `item` and `user` accordingly, and share a `schema` file again. thanks!

**Comment by rnyak** [comment]
@shoyasaxa I think this was resolved by adding `part_size` arg to Dataset class as in this example:
`Dataset(os.path.join(output_path, 'train', '*.parquet'), part_size="500MB")`.

can we close this issue? thanks.

**Comment by shoyasaxa** [comment]
Yes - thank you!
