### ISSUE TITLE
Make RaggedTensors the default for list-columns in the FeatureContext

### ISSUE THREAD

**Issue by marcromeyn** [NVIDIA-Merlin/models#446]
Right now we are converting all features to dense when we store them in the feature-context ([source](https://github.com/NVIDIA-Merlin/models/blob/main/merlin/models/tf/models/base.py#L293)). It would be better to store them as `tf.RaggedTensors`, when retrieving them the user could choose to convert this to sparse or dense. This would have a lower memory footprint.

**Comment by rnyak** [comment]
closing since it was fixed.
