### ISSUE TITLE
[FEA] Create a variant of TwoTowerModel that accepts sequences of past user interactions in the user tower

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/models#459]
# 🚀 Feature request

Currently the `TwoTowerModel` supports in the user/query tower user features (e.g. user id, user demographic features) and/or query features (time features, contextual features).
This request is to create a variant of TwoTowerModel that accepts sequential features from past user sessions, that could be used as a replacement for the user id (for example).

## Motivation

A common use case for two tower retrieval models is using a sequence with the last N user interactions in the user tower instead of the user embedding. 
This approach has some potential advantages:
1.  User interactions sequences could be updated as the user interacts with the system, without having to retrain the corresponding user embedding with the latest sequences.
2. Because of that, this implementation would better address the user cold-start problem, as even if the user were not present in the train set, with a few interactions it would be possible to generate personalized recommendations to him (like in session-based recommendation)

**Comment by rnyak** [comment]
With InputBlockV2 this should be doable.

**Comment by oliverholworthy** [comment]
There's an example of this in [a test here](https://github.com/NVIDIA-Merlin/models/blob/v0.10.0/tests/unit/tf/models/test_retrieval.py#L25)
