### ISSUE TITLE
[BUG] Embedding tables are not created until `model.fit` is called

### ISSUE THREAD

**Issue by radekosmulski** [NVIDIA-Merlin/models#530]
### Bug description

While working on #508 I identified that embedding tables are not created until `model.fit` is called. @rnyak suggested I raise a bug for this.

### Steps/Code to reproduce bug
![image](https://user-images.githubusercontent.com/2444926/175668064-7ea725da-6562-4dd7-8a60-d39bd0007bb3.png)

### Expected behavior
An embedding table is created before `model.fit` is called. 

### Environment details
`nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.05`

**Comment by viswa-nvidia** [comment]
@radekosmulski , please triage this bug and assign priority and severity
