### ISSUE TITLE
[Task] Target generation for Youtube-DNN retrieval model

### ISSUE THREAD

**Issue by sararb** [NVIDIA-Merlin/models#540]
### Description
Implement a mapping function to apply on top of the data loader in order to extract targets from the input sequence.  The goal is to define different strategies for setting the target of the Item Prediction task. 

We particularly want to support 4 different strategies: 

![image](https://user-images.githubusercontent.com/17721108/176234142-8263bee0-1046-4222-8c17-576635866c05.png)

- `Last`:  extract the last non-padded item from the input sequence  and set it as the target.

- `Sliding window`: Generate multiple targets at different positions based on a sliding-window and extend the input batch with the related truncated input sequences. 

- `Random`: Randomly select a cutting point and set the last item as the target. The input sequence is all interactions from the left context. 

-  `Random held-out`: Randomly select a cutting point as the label.  The input sequence is all interactions from both contexts, left and right. 

**Additional context**
In the Youtube-DNN [paper](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45530.pdf), they tested the following label selection strategies: 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/17721108/176217621-653a0532-7217-4189-9740-319ade3c9b6c.png">

**Comment by gabrielspmoreira** [comment]
The PR #745 implements the `last` and `random` strategy. I don't implement there the sliding windows of random proposed here, as multiple epochs with `random` can approximate it. And the random held-out is actually more useful with Masked Language Modeling (BERT-like) training as it includes the right context, which is implemented in PR #775
