### ISSUE TITLE
[Task] Example of training Implicit in Merlin Models 

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/models#561]
### Description
Add an example to train a model with implicit library with Merlin Models:
https://github.com/NVIDIA-Merlin/Merlin/issues/104

**Comment by viswa-nvidia** [comment]
@radekosmulski ,are you working on this now ?

**Comment by radekosmulski** [comment]
Yes, that's correct, I am!

**Comment by rnyak** [comment]
is being worke on https://github.com/NVIDIA-Merlin/models/pull/629
