### ISSUE TITLE
Example of serving Implicit in Merlin Systems

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/models#577]

**Comment by rnyak** [comment]
related https://github.com/NVIDIA-Merlin/systems/pull/134

**Comment by rnyak** [comment]
@radekosmulski can you add some context here, if this requires some features/ops from Merlin Systems?

**Comment by oliverholworthy** [comment]
#134 was merged this week. So can now be tried out for now for creating an example.

**Comment by oliverholworthy** [comment]
#134 was merged this week which provides an operator that can be tried out for use in an example

**Comment by rnyak** [comment]
addressed by https://github.com/NVIDIA-Merlin/systems/pull/194
