### ISSUE TITLE
[Task] InputBlockV2 - Usage in ranking models high-level API

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/models#604]
Change the following higher-level API ranking models to use the new `InputBlockV2`.
This is part of RMP #479, which you can check for more context

- [x] `DCNModel`
- [x] `DeepFMModel`

**Comment by viswa-nvidia** [comment]
@gabrielspmoreira , please follow the template and add the problem statement, goal, constraints and starting point.
