### ISSUE TITLE
[BUG]Flaky unit tests for models

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/models#607]
### Bug description
Unit tests failed for models in this run https://blossom.nvidia.com/sw-gpu-merlin-ci/job/new-test-merlin/717/
This may be due to a flaky unit test. This must be checked in 22.08.

**Comment by viswa-nvidia** [comment]
@rnyak , I see this is blocked. Why is this blocked ?

**Comment by rnyak** [comment]
> @rnyak , I see this is blocked. Why is this blocked ?

I dont remember I set the statues to `blocked`. Please change the status to proper one.

**Comment by rnyak** [comment]
closing since this was already fixed.

**Comment by oliverholworthy** [comment]
Fixed by #766
