### ISSUE TITLE
[Task] Update the high-level API  of retrieval models with new core API 

### ISSUE THREAD

**Issue by sararb** [NVIDIA-Merlin/models#611]
# 🚀 Feature request

The objective is to update retrieval models with the new core API classes once they are completed and tested. The feature includes updating the code base and adding related unit tests.  
Note: The old ItemRetrievalTask and ItemRetrievalScorer will get removed. 

This will fix #498

**Comment by rnyak** [comment]
being fixed by https://github.com/NVIDIA-Merlin/models/pull/790
