### ISSUE TITLE
[Task] Update DLRM to use the new EmbeddingTable

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/models#613]
### Description
Currently DLRM is using a custom input block and the previous `EmbeddingFeatures`. 
This task is about replacing `EmbeddingFeatures` by the new `EmbeddingTable` and also analyzing if DLRM can use the `InputBlockV2` instead of its custom approach to represent features.
Associated to https://github.com/NVIDIA-Merlin/Merlin/issues/479, which you can check for more context

**Comment by oliverholworthy** [comment]
- PR #620 demonstrates how `InputBlockV2` can be used inside the `DLRMBlock` (the existing tests pass, note that the layer names and structure has changed slightly with this change). However, the way it stands, I think it makes the code less clear. And I'm wondering if that may be true in more cases where we are considering replacing usage of the InputBlock with InputBlockV2.

**Comment by oliverholworthy** [comment]
- PR #619 demonstrates how the `EmbeddingFeatures` can be replaced with the `Embeddings` in the `DLRMBlock` (with existing tests passing, note that there is a change to the structure of the layers here). 
  - As it stands, this doesn't make the code any clearer. And seems to remove some functionality - with this change, the intializers and l2_reg from EmbeddingOptions are ignored.

**Comment by sararb** [comment]
Thanks, @oliverholworthy and @gabrielspmoreira for the refactor of DLRM with the updated Embeddings API.  There is an example [notebook](https://github.com/NVIDIA-Merlin/models/blob/main/examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb) that shows how to build the DLRM model from scratch. Should we include the update of this notebook in this ticket?

**Comment by gabrielspmoreira** [comment]
Fixed by #619
