### ISSUE TITLE
[BUG] incorrect dtype of `userId` in generated data for movielens-100k

### ISSUE THREAD

**Issue by radekosmulski** [NVIDIA-Merlin/models#624]
### Bug description

The schema is correct, but the generated data has an incorrect dtype.
![image](https://user-images.githubusercontent.com/2444926/183073846-b258b76d-046e-4f8f-a410-94d1d0a921ac.png)

This leads to errors down the road when building examples
![image](https://user-images.githubusercontent.com/2444926/183075013-5a86b145-1861-4fcc-985a-388cc21ff47b.png)

### Steps/Code to reproduce bug
```
from merlin.core.utils import Distributed
from merlin.models.xgb import XGBoost
import nvtabular as nvt
import numpy as np
from merlin.schema.tags import Tags

from merlin.datasets.synthetic import generate_data
train, valid = generate_data(
    input="movielens-100k",
    num_rows=1000,
    set_sizes=(0.8, 0.2)
)

# some unrelated preprocessing
preprocess_categories = ['movieId', 'userId', 'genres'] >> nvt.ops.Categorify(freq_threshold=2, dtype=np.int32)

train_workflow = nvt.Workflow(preprocess_categories + ['rating', 'userId_count'])
train_transformed = train_workflow.fit_transform(train)

with Distributed():
    model = XGBoost(schema=train_transformed.schema)
    model.fit(
        train_transformed,
        num_boost_round=85,
        verbose_eval=20
)
```

### Environment details
Current main

**Comment by rnyak** [comment]
@radekosmulski shall we move this to NVTabular?

**Comment by radekosmulski** [comment]
@rnyak that is a good question, I am not sure to be honest. The issue is what the dtype, but the code for generating the dataset is part of merlin models, not sure what would be the preferred place for this issue.

Happy to move it over, let me know please if NVTabular would be more appropriate to house this issue 🙂

**Comment by oliverholworthy** [comment]
@radekosmulski You're right about the issue being in the dataset generation code here in Merlin Models. 

I've opened a PR #662 that adds the missing dtype coercion that I think is causing the issue you have observed with the synthetic movielens data.
