### ISSUE TITLE
[BUG] Dimensionality of DotProductInteractionBlock() in DLRM models

### ISSUE THREAD

**Issue by sunnyqywang** [NVIDIA-Merlin/models#643]
### Bug description
In DLRM models, dot products are taken to find pairwise interactions between features. The resulting dimension should be (batch_size, embedding_size + (num_categorical_features + 1) * (num_categorical_features) / 2). But the current implementation results in (batch_size, embedding_size + (embedding_size + 1) * (embedding_size ) / 2). 

### Steps/Code to reproduce bug
[In example "Define your own architecture"
](https://nvidia-merlin.github.io/models/main/examples/06-Define-your-own-architecture-with-Merlin-Models.html) 
The line

>  dlrm_interaction(batch)

results in tensor shape (5, 2080), with 2080 being 64 + 64*65/2.

### Expected behavior

Since there are 5 features (4 categorical and 1 deep continuous), the tensor should have dimension 64+5*4/2=74

**Comment by oliverholworthy** [comment]
Thank you for reporting this issue. 

This has been updated in #637 which is now merged into the main branch. The change will be available in the next release of the library (next week).
