### ISSUE TITLE
[Task] Example for Debugging Merlin Models

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/models#675]
### Description
I want to propose an example, how to debug merlin model architectures and functionality.

Content could be (not limited to it):
- viewing model.layers, explaining the structure
- generating a batch with next(iter(dataloader)) and calling individual model components (e.g. input block, parallel block, etc.)
- can we visualize merlin models with Tensorboard?

**Comment by rnyak** [comment]
related task https://github.com/NVIDIA-Merlin/models/issues/642
