### ISSUE TITLE
[Task] Example notebooks for generation top_k recommendations with ranking and retrieval models

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/models#679]
### Description

Currently none of our example notebooks  have any code script showcasing how one can  do model prediction locally, generate top-K recommendations from the prediction results. This does not include Merlin systems, it is doing offline predictions.

We can either add a new notebook or extend the existing retrieval and ranking notebooks to show such functionality. I think extending the existing notebooks would be better idea.

We have been getting requests for such examples internally or externally and this will be very informative for our users.

**Comment by rnyak** [comment]
This is still being worked on via https://github.com/NVIDIA-Merlin/models/issues/718.

I will create an example for generating topk recommendation for a ranking model, but for retrieval model we still need the https://github.com/NVIDIA-Merlin/models/issues/718 task to be completed to create an example.

Related PRs:

- https://github.com/NVIDIA-Merlin/models/pull/705
- ?

**Comment by bschifferer** [comment]
@sararb do you know if the API update is finished and we can implement this example?

**Comment by rnyak** [comment]
I am closing this since we have an example for generating topK recommendations, merged by https://github.com/NVIDIA-Merlin/models/pull/900
