### ISSUE TITLE
[BUG] merlin models on vertex ai training - cuda error

### ISSUE THREAD

**Issue by tottenjordan** [NVIDIA-Merlin/models#683]
**Describe the bug**
I've been able to train a Merlin model in a Vertex Notebook (using merlin base image). Now I'm trying to train the same model in Vertex AI Training. When training begins, I get this error:

```
numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.7; current version is '7.4'
```

**Steps/Code to reproduce bug**
* I'm building [this dockerfile](https://github.com/tottenjordan/spotify-merlin/blob/main/src/Dockerfile.merlintf), using the below as a base image:
> `FROM nvcr.io/nvidia/merlin/merlin-tensorflow:22.07`

* The error occurs in the `model.fit()` call in [`training_task.py`](https://github.com/tottenjordan/spotify-merlin/blob/main/src/training/train_task.py#L99)

**Expected behavior**
Execute training

**Environment details (please complete the following information):**
 - Environment location: Google Cloud, Vertex AI Training Job
 - Driver:
 
![image](https://user-images.githubusercontent.com/39886184/186285272-27262815-0e49-4a48-8bd9-7ddb064121a8.png)
 

**Additional context**
* [full training package](https://github.com/tottenjordan/spotify-merlin/tree/main/src/training)

**Comment by jperez999** [comment]
Hello @tottenjordan what is the base driver version on the machine? Is that original picture of nvidia-smi output bare-metal or on the actual container?

**Comment by tottenjordan** [comment]
Hey @jperez999 - This should be the container. I think becasue this is running with bash it shouldnt be a driver problem, right?

I think it has to do with either
* how `LD_LIBRARY_PATH` is being set/not set 
* how the other CUDA artifacts are being found/loaded

**Comment by jperez999** [comment]
@tottenjordan 

CUDA artifacts are loaded via the /opt/nvidia/nvidia_entrypoint.sh. I built your dockerfile, and it does not change your entrypoint. This means you should be loading the correct cuda version and all of its relevant artifacts. 

And looking through the container's `LD_LIBRARY_PATH` you have some stuff doubled/tripled up and an extra path **/usr/local/cuda/compat/lib.real** but you are not missing anything.

Normal tensorflow container's LD_LIBRARY_PATH:
```
/usr/local/hugectr/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/lib:/repos/dist/lib:/opt/tritonserver/lib
```

Container built from your dockerfile's LD_LIBRARY_PATH:
```
/usr/local/hugectr/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/lib:/repos/dist/lib:/opt/tritonserver/lib:/usr/local/cuda/compat/lib.real:/usr/local/hugectr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/lib:/repos/dist/lib
```

Next step will be to attempt to repro your issue by producing a synthetic dataset with the same attributes as your dataset and running the same training task.

**Comment by rnyak** [comment]
@tottenjordan is this still an issue? can we close the ticket?

**Comment by tottenjordan** [comment]
thanks @rnyak
