### ISSUE TITLE
[Task] Add example of Wide&Deep ranking model

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/models#704]
### Description
Add an example of Wide&Deep ranking model in the [03-Exploring-different-models.ipynb](https://github.com/NVIDIA-Merlin/models/blob/main/examples/03-Exploring-different-models.ipynb) notebook.

**Comment by viswa-nvidia** [comment]
@gabrielspmoreira , please link the PR and close
