### ISSUE TITLE
[Task] Add ToTarget transform

### ISSUE THREAD

**Issue by marcromeyn** [NVIDIA-Merlin/models#720]
Right now it’s quite awkward to use certain columns from a schema as a target. Right now we assume that these targets are tagged as part of nvtabular which is not always the case. In order to make this easier we could have a `ToTarget` transform that can be used as part of our data-loader.

### Starting point

```python

class ToTarget(Layer):
	def __init__(
		self, 
		schema,
		*target: Union[Schema, ColSchema, str], 
		one_hot=False
	):
		...

	def call(self, inputs: TabularData, targets=None, testing=False, **kwargs) -> Prediction:
		...

	def compute_output_schema(self, input_schema) -> Schema:
		...
```

**Comment by karlhigley** [comment]
For reference, here's how NVT implements that: https://github.com/NVIDIA-Merlin/NVTabular/blob/main/nvtabular/ops/add_metadata.py#L44

As far as I understand, the existing way to use that operator with the dataloaders is to build a workflow containing whatever modifications you want to make to the input data and construct a dataloder with the (lazily evaluated) result of the workflow transform, like `Dataloader(workflow.transform(dataset))`
