### ISSUE TITLE
[Task] Transformer-Based End-To-End Example with TensorFlow Merlin Models

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/models#734]
This ticket is to provide and End-To-End example in Merlin Models for a transformer-based model.

We will add serving to https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/transformers-next-item-prediction.ipynb . @radekosmulski started a PR, but we are blocked on the implementation https://github.com/NVIDIA-Merlin/models/pull/1045

**Comment by bschifferer** [comment]
@marcromeyn @viswa-nvidia can you provide the dependency for the tickets? Which other tickets need to be finished that we can provide the example?

**Comment by bschifferer** [comment]
What do we want to demonstrate? Is this the Transformer4Rec examples in Merlin Models with Tensorflow instead of PyTorch? Do we need any other system components (e.g. candidate retrieval, feature store)?

**Comment by bschifferer** [comment]
Updating RecSys2022 with Transformer4Rec

**Comment by bschifferer** [comment]
Merlin Models Examples - Transformer4Rec Examples:
Repository Merlin/models:
- Updating RecSys2022 with Transformer4Rec

Repository Merlin/Merlin
- UseCase #1: Low number of items (<2000 items) - direkt ranking (training+serving)
- UseCase #2: More Items - extract embeddings and use ANN (training+serving)

Dataset - TBD:
Potential: dressipi, h&m, ecommerce, booking.com?

**Comment by bschifferer** [comment]
Details are added here: https://docs.google.com/document/d/1Zi0SNHHiN72wYIwpkKx-u5xqC35YvlZjNTKUosRuQds/edit
