### ISSUE TITLE
[BUG] Merlin TF two-tower - error using `tf.distribute.MirroredStrategy()`

### ISSUE THREAD

**Issue by tottenjordan** [NVIDIA-Merlin/models#744]
### Bug description

Training a Merlin (TF) Two-Tower model in Vertex AI Training
* when scaling to **single node, multi-GPU**, i encounter the following error:

'''
ValueError: `NONE` variable synchronization mode is not supported with tf.distribute strategy. Please change the `synchronization` for variable: should_compute_train_metrics_for_batch
'''
Which seems to be referring to [this line](https://github.com/NVIDIA-Merlin/models/blob/main/merlin/models/tf/models/base.py#L298) in merlin models code

### Steps/Code to reproduce bug

My [training code](https://github.com/tottenjordan/spotify-merlin/blob/main/src/training/train_task.py#L189) works when specifying:
* `strategy = tf.distribute.OneDeviceStrategy()` 
* a single A100 GPU ('a2-highgpu-1g' in GCP)

The error occurs during `model.compile` when switching to single node, multi-device:
* `strategy = tf.distribute.MirroredStrategy()`
* Four A100s ('a2-highgpu-4g' in GCP)

```
        model.compile(
            optimizer="adam", 
            run_eagerly=False, 
            metrics=[mm.RecallAt(1), mm.RecallAt(10), mm.NDCGAt(10)]
        )
```
found [here](https://github.com/tottenjordan/spotify-merlin/blob/main/src/training/train_task.py#L198)

### Expected behavior
ability to train two-tower model on a single node, multiple GPUs 

### Environment details
- Merlin version: `merlin-models==0.6.0+8.g042ee198` (using the contianer: `nvcr.io/nvidia/merlin/merlin-tensorflow:22.07`)
- Platform: Google Cloud
- Python version: 3.8
- PyTorch version (GPU?): N/A
- Tensorflow version (GPU?): 2.9

**Comment by gabrielspmoreira** [comment]
Thanks for filling this issue @tottenjordan 
I did an initial investigation and found other errors occur when `tf.distribute.MirroredStrategy()` is used to define and train Merlin models, reported in #764 . So `MirroredStrategy` is currently not supported by Merlin Models for data parallel training. We plan to have multi-GPU data parallel training addressed soon by an upcoming release.

**Comment by EvenOldridge** [comment]
Closing as this isn't something we currently support.  @tottenjordan if you're interested in this functionality can you please file as a feature request.
