### ISSUE TITLE
[BUG] Fail to load TwoTowerModel using tf.keras.models.load_model or pickle

### ISSUE THREAD

**Issue by zhiruiwang** [NVIDIA-Merlin/models#753]
### Bug description

In [RecSys 22 Tutorial notebook 4](https://github.com/NVIDIA-Merlin/publications/blob/main/tutorials/RecSys22tutorial/04-Building-multi-stage-RecSys.ipynb), I added a new step to save the TwoTowerModel model_tt to disk, it saved successfully but returns a warning
```
WARNING:absl:Found untraced functions such as model_context_layer_call_fn, model_context_layer_call_and_return_conditional_losses, item_retrieval_scorer_layer_call_fn, item_retrieval_scorer_layer_call_and_return_conditional_losses, user_id_layer_call_fn while saving (showing 5 of 66). These functions will not be directly callable after loading.
```
And when I try to use `tf.keras.models.load_model` to load this model, it returns an error
```
AssertionError: Found 1 Python objects that were not bound to checkpointed values, likely due to changes in the Python program. Showing 1 of 1 unmatched objects: [<tf.Variable 'query:0' shape=(None, 64) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>]
```
The same warning and error happen when I use pickle to save and load the model.

I see in the unit test the saving and loading of query tower and item tower of TwoTowerModel are being tested, wonder if saving and loading the entire model is being tested? Not sure if it's related to https://github.com/NVIDIA-Merlin/models/issues/500 or https://github.com/NVIDIA-Merlin/models/issues/677

Interestingly, when saving and loading a DLRM model, it returns the same warning, but the model can be loaded successfully

### Steps/Code to reproduce bug

1. In [RecSys 22 Tutorial notebook 4](https://github.com/NVIDIA-Merlin/publications/blob/main/tutorials/RecSys22tutorial/04-Building-multi-stage-RecSys.ipynb), run the notebook after the training of model_tt
2. Run `model_tt.save(os.path.join(BASE_DIR, "model_tt"))`
3. Run `tf.keras.models.load_model(os.path.join(BASE_DIR, "model_tt"))`

Alternatively:
2. Run 
```
import pickle

with open(os.path.join(BASE_DIR, "model_tt.pkl"), 'wb') as outp:
    pickle.dump(model_tt, outp, pickle.HIGHEST_PROTOCOL)
```
3. Run
```
with open(os.path.join(BASE_DIR, "model_tt.pkl"), 'rb') as inp:
    model_tt = pickle.load(inp)
```

### Environment details
- Docker image: merlin-tensorflow:22.07 with merlin-models updated to the latest release

**Comment by rnyak** [comment]
@zhiruiwang  Currently you can save and load back the query tower but not the entire TT model. we are currently working on saving/loading back the entire Two-Tower model.

**Comment by zhiruiwang** [comment]
@rnyak Thanks! 

After looking into the source code, I figured out a way to save and load back both the query tower and item tower to make Faiss work, instead of using the entire TT model. Just putting the code out here:

Save item block along with query block in training:
```
query_tower = model_tt.retrieval_block.query_block()
query_tower.save(os.path.join(BASE_DIR, "query_tower"))

item_block = model_tt.retrieval_block.item_block()
item_block.save(os.path.join(BASE_DIR, "item_tower"))
```

In init feast part of the inference, replace
```
item_embs = model_tt.item_embeddings(
    Dataset(item_features, schema=schema), batch_size=1024
)
item_embs_df = item_embs.compute(scheduler="synchronous")
```
with
```
item_tower = tf.keras.models.load_model(os.path.join(BASE_DIR, "item_tower"))

from merlin.models.tf.utils.batch_utils import TFModelEncode
get_item_emb = TFModelEncode(item_tower, batch_size=1024, output_concat_func=np.concatenate)
dataset = unique_rows_by_features(Dataset(item_features, schema=item_block.schema), Tags.ITEM, Tags.ITEM_ID).to_ddf()
embeddings = dataset.map_partitions(get_item_emb)
item_embs_df = embeddings.compute(scheduler="synchronous")
```

**Comment by viswa-nvidia** [comment]
@rnyak , please review and close

**Comment by rnyak** [comment]
closing this issue since this issue is not a blocker for the user.
