### ISSUE TITLE
[FEA] Easy functionality for using class_weights and sample_weights for Retrieval models

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/models#789]
# 🚀 Feature request

- Since Inbatch sampler converts the retrieval task to multi-class classification,  we need an easy functionality to be able to use `class_weight` and `sample_weight` args in the model.fit() for retrieval models, without users to deal with customization.
- add unit test for using `sample_weight` and `class_weight` args for retrieval tasks in [here](https://github.com/NVIDIA-Merlin/models/blob/main/tests/unit/tf/models/test_retrieval.py)
- we need examples or code snippets in the docs to showcase the functionality

This request comes from a customer.

**Comment by bschifferer** [comment]
Let's add a documentation (inline docstring) for the feature
