### ISSUE TITLE
[BUG] InputBlock gives incorrect shape for continuous sequence features

### ISSUE THREAD

**Issue by zhiruiwang** [NVIDIA-Merlin/models#814]
### Bug description

When using InputBlock to take in continouse sequence features, expected shape would be `[batch_size, seq_length, num_cont_features]`, but instead if became `[batch_size, num_cont_features*seq_length]`. 

And when concatenated with categorical sequence features, the tensor got broadcasted and the resulting tensor became `[batch_size, seq_length, sum(cat feature embedding sizes)+num_cont_features*seq_length]`, while the expected shape would be `[batch_size, seq_length, sum(cat feature embedding sizes)+num_cont_features]`

### Steps/Code to reproduce bug

```
import merlin.models.tf as mm
from merlin.io import Dataset
from merlin.models.tf.loader import Loader
from merlin.schema import Tags

import tensorflow as tf

from merlin.datasets.synthetic import generate_data
sequence_testing_data = generate_data("sequence-testing", num_rows=1000)

loader = Loader(sequence_testing_data, batch_size=8, shuffle=False)
batch = mm.sample_batch(loader, 8, include_targets=False)

cont_seq_schema = sequence_testing_data.schema\
  .select_by_tag(Tags.SEQUENCE)\
  .select_by_tag(Tags.CONTINUOUS)

cont_seq_inputs = mm.InputBlock(
        cont_seq_schema ,
        aggregation='concat',
        seq=True,
        max_seq_length=4
)

cont_seq_inputs(batch).shape
```
Out[11]: TensorShape([8, 20]), which is `[batch_size, num_cont_features*seq_length]`. This is expected to be [8, 4, 5]

```
import merlin.models.tf as mm
from merlin.io import Dataset
from merlin.models.tf.loader import Loader
from merlin.schema import Tags

import tensorflow as tf

from merlin.datasets.synthetic import generate_data
sequence_testing_data = generate_data("sequence-testing", num_rows=1000)

loader = Loader(sequence_testing_data, batch_size=8, shuffle=False)
batch = mm.sample_batch(loader, 8, include_targets=False)

seq_schema = sequence_testing_data.schema\
  .select_by_tag(Tags.SEQUENCE)

seq_inputs = mm.InputBlock(
        seq_schema,
        aggregation='concat',
        seq=True,
        max_seq_length=4
)

seq_inputs(batch).shape
```
Out[12]: TensorShape([8, 4, 148]), which is `[batch_size, seq_length, sum(cat feature embedding sizes)+num_cont_features*seq_length]`. This is expected to be [8, 4, 64+64+5=133]

### Expected behavior

At https://github.com/NVIDIA-Merlin/models/blob/main/merlin/models/tf/inputs/base.py#L178
```
        pre = None
        if max_seq_length and seq:
            pre = ListToDense(max_seq_length)
        branches["continuous"] = ContinuousFeatures.from_schema(  # type: ignore
            schema,
            tags=continuous_tags,
            pre=pre,
        )
```
Might need to be refactored to:
```
        pre = None
        post = None
        if max_seq_length and seq:
            pre = ListToDense(max_seq_length)
            post = ExpandDims()
        branches["continuous"] = ContinuousFeatures.from_schema(  # type: ignore
            schema,
            tags=continuous_tags,
            pre=pre,
            post=post
        )
```
To correct the shape

**Comment by rnyak** [comment]
@zhiruiwang thanks for reporting the issue. we''ll look into that.

**Comment by rnyak** [comment]
@zhiruiwang for your first case after recent fixes, I can get `TensorShape([8, 4, 5])` shape. you can test at your end by pulling the latest main branch, if that's fine.  In the meantime we are investigating if there is any issue with the new api `InputBlockV2`.  Can you also tell us more about what use-case you are interested in? a session-based model or sequential model using RNN-based methods? or transformer based models? or something else? thanks.

**Comment by zhiruiwang** [comment]
@rnyak Thanks! The first case is working as expected, but the second case is no longer working... However, I think I should switch to InputBlockV2 instead, so I tried switching out `InputBlock` with `InputBlockV2`. The third dimensions are working fine in both cases:

```
import merlin.models.tf as mm
from merlin.io import Dataset
from merlin.models.tf.loader import Loader
from merlin.schema import Tags

import tensorflow as tf

from merlin.datasets.synthetic import generate_data
sequence_testing_data = generate_data("sequence-testing", num_rows=1000)

loader = Loader(sequence_testing_data, batch_size=8, shuffle=False)
batch = mm.sample_batch(loader, 8, include_targets=False)

cont_seq_schema = sequence_testing_data.schema\
  .select_by_tag(Tags.SEQUENCE)\
  .select_by_tag(Tags.CONTINUOUS)

# cont_seq_inputs = mm.InputBlock(
#         cont_seq_schema ,
#         aggregation='concat',
#         seq=True,
#         max_seq_length=4
# )

cont_seq_inputs = mm.InputBlockV2(
        cont_seq_schema,
        aggregation="concat",
    )

cont_seq_inputs(batch).shape
```
Out[18]: TensorShape([8, None, 5])

```
import merlin.models.tf as mm
from merlin.io import Dataset
from merlin.models.tf.loader import Loader
from merlin.schema import Tags

import tensorflow as tf

from merlin.datasets.synthetic import generate_data
sequence_testing_data = generate_data("sequence-testing", num_rows=1000)

loader = Loader(sequence_testing_data, batch_size=8, shuffle=False)
batch = mm.sample_batch(loader, 8, include_targets=False)

seq_schema = sequence_testing_data.schema\
  .select_by_tag(Tags.SEQUENCE)

# seq_inputs = mm.InputBlock(
#         seq_schema,
#         aggregation='concat',
#         seq=True,
#         max_seq_length=4
# )

seq_inputs = mm.InputBlockV2(
        seq_schema,
        aggregation="concat",
        categorical=mm.Embeddings(
            seq_schema.select_by_tag(Tags.CATEGORICAL), dim=64, sequence_combiner=None
        ),
    )

seq_inputs(batch).shape
```
Out[16]: TensorShape([8, None, 133])

My only question is, without the argument `max_seq_length=4`, how would I make it show the second dimension as `4` instead of `None`?

**Comment by zhiruiwang** [comment]
And in terms of use cases, we have both session-based and sequential recommendation in mind, and both RNN-based and Transformer-based models in mind. We noticed that RNN-based models, especially bi-LSTM, is performing better than Transformer models, when the sequence length is short. So we think RNN-based models and Transformer-based models are equally important.

**Comment by rnyak** [comment]
> And in terms of use cases, we have both session-based and sequential recommendation in mind, and both RNN-based and Transformer-based models in mind. We noticed that RNN-based models, especially bi-LSTM, is performing better than Transformer models, when the sequence length is short. So we think RNN-based models and Transformer-based models are equally important.

That's good. I am working on an example nb that uses bi-lstm and XLNet (transformer model) that will be published soon. Hope that will help.

**Comment by rnyak** [comment]
@zhiruiwang you can do something like this: `seq_inputs(batch).to_tensor().shape`. this will print out `TensorShape([8, 4, 133])`. would that be helpful?

Besides, please checkout this updated example notebook: https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb


I am closing this issue since this is no longer a bug but please open another if you have any questions or issues. thanks!

**Comment by zhiruiwang** [comment]
Thanks! Yes this issue has been resolved. Will check out the example notebook!
