### ISSUE TITLE
[Task] Add RNN-based model apis for session-based recommendation

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/models#819]
### Description

Currently there is no out-of-the-box api for creating an LSTM, BiLSTM and GRU architectures for a session-based (or sequential) task.

- For LSTM , I assume we'd use tf.keras.layers.LSTM api.
- For BiLSTM shall we use [tf.keras.layers.Bidirectional](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Bidirectional)?
- For GRU, can we not port GRU4Rec model code from TF4Rec to Merlin Models?

Looks like there were two tickets before but they were closed without completion:

https://github.com/NVIDIA-Merlin/models/issues/732
https://github.com/NVIDIA-Merlin/models/issues/733

**Comment by zhiruiwang** [comment]
Just a wild suggestion, maybe you can also add SAS4Rec by using tf.keras.layers.MultiHeadAttention. I assume it will be a very similar block structure once LSTM and GRU blocks are done

**Comment by rnyak** [comment]
closing this since we are creating an example for  BiLSTM where we can easily  use [tf.keras.layers.Bidirectional](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Bidirectional)?
