### ISSUE TITLE
[BUG] `get_booking()` from `merlin.datasets.ecommerce` doesn't work with a path without a `.` (dot)

### ISSUE THREAD

**Issue by radekosmulski** [NVIDIA-Merlin/models#873]
### Bug description
 `get_booking()` from `merlin.datasets.ecommerce` doesn't work with a path without a `.` (dot)

![image](https://user-images.githubusercontent.com/2444926/201001522-ed94dbee-16e7-4e0c-bdd5-548f5bd4ea3a.png)

Calling the function without a parameter doesn't work either.
![image](https://user-images.githubusercontent.com/2444926/201001564-5b551499-b7c5-4b5f-baea-7fafdc6ed499.png)

### Steps/Code to reproduce bug
```
from merlin.core.dispatch import get_lib
from merlin.datasets.ecommerce import get_booking
import numpy as np

from nvtabular import *
from nvtabular import ops
from merlin.models.tf import Loader
from merlin.schema.tags import Tags

get_booking('/workspace')
```

### Expected behavior
One can specify a path where the data will be downloaded to.

### Environment details
Tensorflow container 22.10

**Comment by rnyak** [comment]
closing this since this was solved via https://github.com/NVIDIA-Merlin/models/pull/874
