### ISSUE TITLE
[DOC] Revise and improve 07-Train-traditional-ML-models-using-the-Merlin-Models-API notebook

### ISSUE THREAD

**Issue by bbozkaya** [NVIDIA-Merlin/models#906]
Client feedback suggests that the portion of this notebook on training implicit models is rather limited. It currently includes minimal steps to "fit" and "train" two implicit models + LightFM with some parameters (eg. warp loss) set, but not explained in detail, and according to the client, the lack of detail makes it hard to follow what exactly is going on. Could we:

- add further text explaining more about the models we included in this section (and why), and provide links (for the two implicit models) for reference
- add text explaining why some model parameters are chosen as they are (with other possible options) and what some of the hidden/assumed parameters are
- show data records (eg. train.head) going into the training as well as results of prediction and brief explanations
- show evaluation metrics (not just the line to execute metric calculation) and interpret them
- describe limitations of the current implicit API in Merlin Models. For example, based on the way the wrapper code is currently written in Merlin Models, there is an assumption that we're in a user-item recommender setting and item-item recommender setting is missing. However, in Ben's library there is model.similar_items(itemid) functionality.

**Comment by radekosmulski** [comment]
hey @bbozkaya -- thank you for reporting this! taking a closer look, will keep updating this issue as we make progress!

**Comment by radekosmulski** [comment]
Hey @bbozkaya could I please ask you to take a look at the updates [here](https://github.com/NVIDIA-Merlin/models/blob/update_07/examples/07-Train-traditional-ML-models-using-the-Merlin-Models-API.ipynb)? do you think we might still be missing something here?

thank you so much! 🙂

**Comment by bschifferer** [comment]
@bbozkaya can we merge Radek's PR?

**Comment by bbozkaya** [comment]
I still don't see one of the typos I asked in there. So I am not sure, did @radekosmulski say all changes were committed?
