### ISSUE TITLE
[BUG] Error when loading the session-based model, layer saved without config

### ISSUE THREAD

**Issue by FredHJC** [NVIDIA-Merlin/models#913]
### Bug description

Escalate the issue to BUG for more awareness. [here](https://github.com/NVIDIA-Merlin/models/issues/908)

### Steps/Code to reproduce bug

1. Train and save the session-based model as shown in the [sample notebook](https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb).
2. Load the model

![image](https://user-images.githubusercontent.com/24794992/205665763-debfa4ca-c22c-476f-9dfa-b108c8433657.png)

**Comment by rnyak** [comment]
closing since same bug was reported here https://github.com/NVIDIA-Merlin/models/issues/908
