### ISSUE TITLE
[BUG]  ModuleNotFoundError: No module named 'merlin.dataloader'

### ISSUE THREAD

**Issue by vs385** [NVIDIA-Merlin/models#923]
### Bug description
Git cloned the main branch of merlin-models inside <my_project>  since I'm trying to use TwoTowerModelV2
When running my entry point, I get the below error:
Traceback (most recent call last):
  File "<my_model_script>.py", line 1, in <module>
    import merlin.models.tf as mm
  File "/<my_project>/merlin/models/tf/__init__.py", line 20, in <module>
    from merlin.dataloader.tf_utils import configure_tensorflow
ModuleNotFoundError: No module named 'merlin.dataloader'

### Steps/Code to reproduce bug

1. git clone -b main https://github.com/NVIDIA-Merlin/models.git
2. pwd in <my_project>
3. cp -r models/merlin .
4. run <my_entrypoint_retrieval_model>.sh --params

### Expected behavior
Should be run without this error... How to go around using this? And when will this be released so I don't have to git clone but the latest code will be running from inside the container?

### Environment details

Merlin version: nvcr.io/nvidia/merlin/merlin-tensorflow:22.10
Platform: ec2 g5 instance linux
Python version: 3.8.10
PyTorch version (GPU?):
Tensorflow version (GPU?): tensorflow 2.9.1+nv22.8

**Comment by rnyak** [comment]
@vs385 hello. can you share `<my_entrypoint_retrieval_model>.sh` file?

**Comment by vs385** [comment]
Hi @rnyak , thanks for getting back... I was able to pip install . in the cloned merlin folder as instructed above, and tried running one of the notebooks in the examples folder afterwards, and the error didn't show up.
Also, I've pulled the latest image nvcr.io/nvidia/merlin/merlin-tensorflow:22.11 (I was using 22.10 before) and the merlin Models project baked in the image has the latest TwoTowerModelV2, so I won't need to git clone the main head of the repo thankfully.
Thanks for your help with this issue, marking this as closed :)
