### ISSUE TITLE
[BUG]  print(os.getenv("OMPI_COMM_WORLD_SIZE"))  returns None

### ISSUE THREAD

**Issue by ssubbayya** [NVIDIA-Merlin/models#963]
### Steps/Code to reproduce bug

import horovod.tensorflow.keras as hvd
import os
hvd.init()
print(os.getenv("OMPI_COMM_WORLD_SIZE"))

### Environment details. [nvcr.io/nvidia/merlin/merlin-tensorflow:22.12](http://nvcr.io/nvidia/merlin/merlin-tensorflow:22.12)
- Merlin version: 
- Platform:
- Python version: 3.8
- PyTorch version (GPU?):
- Tensorflow version (GPU?): 2.10.0

**Comment by rnyak** [comment]
@ssubbayya is your model a custom Tensorflow model? or you are using Merlin Models Api?

**Comment by ssubbayya** [comment]
ngpus: 4
image: [nvcr.io/nvidia/merlin/merlin-tensorflow:22.12](http://nvcr.io/nvidia/merlin/merlin-tensorflow:22.12)

**Comment by edknv** [comment]
Hello @ssubbayya, thanks for trying out Merlin Models. Sorry if I'm not understanding your question, but horovod should work in the container without the `OMPI_COMM_WORLD_SIZE` variable having been set. I would suggest using something like the following as a starting point.

main.py
```python
import horovod.tensorflow.keras as hvd
  
hvd.init()

size = hvd.size()
rank = hvd.rank()

print("size:", size)
print("rank:", rank)
```

command
```shell
horovodrun -np 2 python main.py
```

output
```
[1,1]<stdout>:size: 2
[1,1]<stdout>:rank: 1
[1,0]<stdout>:size: 2
[1,0]<stdout>:rank: 0
````

**Comment by edknv** [comment]
Closing this. Please feel free to reopen if you are still having issues or have any questions.
