### ISSUE TITLE
[QST]: Error while running batch predict. 

### ISSUE THREAD

**Issue by Abhinavb08** [NVIDIA-Merlin/models#965]
# ❓ Questions & Help

## Details

I ran the DLRM ranking model from the example notebook on the Merlin GitHub account. I could successfully train the model, but I couldn't run inference on the test/validation set. I made use of batch_predict method to get predicted output, but it failed. Please let me know if there's any parameter that I missed, or perhaps there is another method for generating inference. 

Example notebook link: https://github.com/NVIDIA-Merlin/models/blob/main/examples/04-Exporting-ranking-models.ipynb

To reproduce the error, you can simply run the entire notebook, and then run the below code.

**Batch predict code**
df = model.batch_predict(valid, batch_size=512)

**Error**
ValueError: Metadata inference failed in `<merlin.models.tf.utils.batch_utils.TFModelEncode `.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
IndexError('tuple index out of range')

**Comment by rnyak** [comment]
@Abhinavb08 did you try `model.predict(valid, batch_size=1024)` ? you can replace `valid` with your test set.  Note that It is a `dataset` object.

**Comment by rnyak** [comment]
@Abhinavb08 I am closing this since we did not hear from you. if you still have a question, please reopen. thanks!

**Comment by liyunrui** [comment]
Hi I got same issue for using model.batch_predict

metrics_ncf = model.batch_predict(valid, batch_size=1024)
metrics_ncf


ValueError: Metadata inference failed in `<merlin.models.tf.utils.batch_utils.TFModelEncode `.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
IndexError('tuple index out of range')

Traceback:
---------
  File "/home/ec2-user/anaconda3/envs/rapids-22.08/lib/python3.8/site-packages/dask/dataframe/utils.py", line 195, in raise_on_meta_error
    yield
  File "/home/ec2-user/anaconda3/envs/rapids-22.08/lib/python3.8/site-packages/dask/dataframe/core.py", line 6413, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/ec2-user/anaconda3/envs/rapids-22.08/lib/python3.8/site-packages/merlin/models/tf/utils/batch_utils.py", line 52, in __call__
    output_names = self.output_names or [str(i) for i in range(outputs.shape[1])]

**Comment by liyunrui** [comment]
It's weird. I found you have unit-test[1]. But, I still get same error.

[1].https://github.com/NVIDIA-Merlin/models/blob/046077b8939fb98e9e94fe764b84340be3ecd961/tests/unit/tf/utils/test_batch.py

**Comment by liyunrui** [comment]
@rnyak 
model.predict() It works. but model.batch_predict() has troubles.
Thanks
