### ISSUE TITLE
[BUG] Error happening on executing MTL notebooks under example/usecase

### ISSUE THREAD

**Issue by liyunrui** [NVIDIA-Merlin/models#977]
### Bug description

1. Run the cell for multi-task learning [noteobok](https://github.com/NVIDIA-Merlin/models/blob/2721cc3dfd1941bccd43d831231afc30fd40e177/examples/usecases/ranking_with_multitask_learning.ipynb)

### Environment details
The way I installed is using conda and follow [here](https://github.com/NVIDIA-Merlin/models/issues/962#issuecomment-1419175438)
- Merlin version: 
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):

### Additional context

```
      4 NUM_ROWS = os.environ.get("NUM_ROWS", 100_000)
      5 NUM_ROWS = 1
----> 6 train_ds, valid_ds = generate_data("tenrec-video", int(NUM_ROWS), set_sizes=(0.8, 0.2))
      7 schema = train_ds.schema

File ~/anaconda3/envs/rapids-22.08/lib/python3.8/site-packages/merlin/datasets/synthetic.py:111, in generate_data(input, num_rows, set_sizes, min_session_length, max_session_length, device)
    109     elif not os.path.exists(input):
    110         closest_match = difflib.get_close_matches(input, KNOWN_DATASETS.keys(), n=1)
--> 111         raise ValueError(f"Unknown dataset {input}, did you mean: {closest_match[0]}?")
    113     schema = _get_schema(input)
    114 elif isinstance(input, Schema):

IndexError: list index out of range
```

**Comment by rnyak** [comment]
@liyunrui can you give us a bit more info about your env? where do you run this? in a cloud instance?  are you using merlin-models main branch?

I am not able to reproduce your error. are you able to import merlin libs . can you run the following and see if you are able to do the imports properly?
```
import merlin.models.tf as mm
from merlin.schema.tags import Tags
from merlin.datasets.synthetic import generate_data
```

generally `IndexError: list index out of range` comes when there is no dataset in the folder.  

Are you installing `rapids` via conda? We recommend you to install Merlin via with `pip` in your conda env, if you want to use `conda`. Note that you dont have to use conda to install `cudf` and `dask_cudf`. you can install it via this command:

`pip install rmm-cu11==22.10.0 cudf-cu11==22.10.0 dask-cudf-cu11==22.10.0 --extra-index-url=https://pypi.nvidia.com/`

Please check out the other [ticket](https://github.com/NVIDIA-Merlin/models/issues/962#issuecomment-1419175438) that you follow, there are some updates there.

**Comment by liyunrui** [comment]
Hi rnyak,
Thanks for your reply.
Yes. I'm running on AWS SageMaker instance. And i can import code you suggested

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/22557099/220683972-978c85d7-f11e-461c-bcd3-36fc3fcd64bf.png">

**Comment by rnyak** [comment]
@liyunrui are you still having the issue? can you send us `pip list` output in a .txt file. are you able to run `01` and `02` notebooks in this [folder](https://github.com/NVIDIA-Merlin/Merlin/tree/main/examples/getting-started-movielens)? can you please test?

**Comment by rnyak** [comment]
I closed this issue due to lack of activity in the last couple weeks.
