### ISSUE TITLE
[QST] Is it possible to use the item and user embeddings generated from a retrieval model as input embeddings to DLRM model ?

### ISSUE THREAD

**Issue by Tselmeg-C** [NVIDIA-Merlin/models#990]
# ❓ Questions & Help

**Comment by rnyak** [comment]
@Tselmeg-C  do you want to feed these pre-trained embeddings to DLRM model as an input feature? like continuous features? something like below:

![image](https://user-images.githubusercontent.com/16246900/219511355-f3bfdf90-b74e-4494-819c-7871f843cb67.png)


OR?

**Comment by Tselmeg-C** [comment]
@rnyak I guess so, actually not quite sure how it works. I have extracted item and user embeddings from two-tower retriebel model and write them out as parques file. They look like this currently. I am wandering how to feed them to the 'embedding' arg of mm.DLRMModel. Not quite clear how this API works 
![image](https://user-images.githubusercontent.com/64394100/219583020-72fae963-5926-462f-a384-1b3fe5a2a642.png)

**Comment by rnyak** [comment]
do you want to feed these embedding to the model's embedding layer?  and then you want these embeddings to be trainable or not trainable? can you explain us more what's in your mind before focusing on how to do part? 

we have an [example](https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/entertainment-with-pretrained-embeddings.ipynb) feeding pre-trained embeddings to the embedding layer. Can you please take a look if that's what you want to do?

**Comment by Tselmeg-C** [comment]
> do you want to feed these embedding to the model's embedding layer? and then you want these embeddings to be trainable or not trainable? can you explain us more what's in your mind before focusing on how to do part?
> 
> we have an [example](https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/entertainment-with-pretrained-embeddings.ipynb) feeding pre-trained embeddings to the embedding layer. Can you please take a look if that's what you want to do?

Hi @rnyak, thanks for ur reply. 
I am still trying to create the exact [multi-stage recsys workflow](https://github.com/NVIDIA-Merlin/Merlin/tree/main/examples/Building-and-deploying-multi-stage-RecSys) using my own data, and intend to use is in production. I wanted to feed the embeddings extracted from the two-tower model to the DLRM model's embedding layer. I guess these should be trainable if the ranking model performance is better than two-tower and the item embedding was able to be extracted after the training. Because I would expect those embeddings to be an even better representation of the items than the embedding from the two-tower model (in my case the two-tower performance was not optimal, with auc 0.72). But I am not sure if the re-trained embedding is extractable after training a ranking model, and even if they could be extracted, I am not sure if they could be used in the following steps in the 'deploy' notebook (specifically for queryfaiss to get the closest neighbor candidates).

**Comment by rnyak** [comment]
@Tselmeg-C I am not sure about your motivation about extracting embeddings from the second stage, DLRM model. What are you going to do after extracting embeddings from DLRm model? 

this scenario should be currently doable:

`train a two-tower model as candidate generation model --> extract user and item embeddings --> feed the embeddings to embedding layer or a ranking model (e.g. DLRM) --> train the ranking model --> serve this pipeline on Triton using Merlin Systems library` 

be sure to use the same exact user and item catalog on both Two-tower model (retrieval) and DLRM model (ranking).

you can check this example [example](https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/entertainment-with-pretrained-embeddings.ipynb) for feeding pre-trained embeddings to the embedding layer. In this example we used DCN as ranking model. you can use DCN or change it to DLRM.  Once you extract user and item embeddings from Two-tower model you can store them as numpy array and then assign them to the `embeddings_initializer` something like below. Please follow the example notebook and customize it based on your dataset columns.

```
embed_dims = {}
pretrained_item_embs = <your numpy array that stores embeddings>
embed_dims["item_id"] = pretrained_item_embs.shape[1]

embeddings_init={
    "item_id": mm.TensorInitializer(pretrained_item_embs),
}

embeddings_block = mm.Embeddings(
    train.schema.select_by_tag(Tags.CATEGORICAL),
    infer_embedding_sizes=True,
    embeddings_initializer=embeddings_init,
    trainable={'movieId': True},    # you can set trainable False if you want to freeze these embeddings during training.
    dim=embed_dims,
)
```

**Comment by rnyak** [comment]
@Tselmeg-C I am closing this ticket since we did not hear from you recently. if you have further questions, you can reopen this ticket. thanks.
